name: Build Electron App

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Select OS to build"
        required: true
        default: "windows"
        type: choice
        options:
          - windows
          - linux
      version:
        description: "App version (x.x.x)"
        required: true
        default: "1.0.0"

jobs:
  build-windows:
    if: ${{ github.event.inputs.os == 'windows' }}
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Windows EXE
        run: npm run electron:build:win

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shop_flow_${{ github.event.inputs.version }}_windows
          path: |
            dist-electron/**/*.exe


  build-linux:
    if: ${{ github.event.inputs.os == 'linux' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Linux DEB
        run: npm run electron:build:linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shop_flow_${{ github.event.inputs.version }}_linux
          path: |
            dist-electron/**/*.deb
